CREATE TABLE PEDIDO (_ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, ESTADO TEXT);
CREATE TABLE PRODUCTO (_ID INTEGER PRIMARY KEY AUTOINCREMENT, CODIGO_BARRAS INTEGER, NOMBRE TEXT, MARCA TEXT , PRECIO REAL , CATEGORIA TEXT, DESCRIPCION TEXT);
CREATE TABLE SUPERMERCADO(_ID INTEGER PRIMARY AUTOINCREMENT, NOMBRE TEXT, DIRECCION TEXT, TELEFONO INTEGER, CORREO TEXT, LATITUD REAL, LONGITUD REAL);


INSERT INTO PEDIDO (NOMBRE,ESTADO) VALUES ('compra ENERO 2017','finalizado');
INSERT INTO PEDIDO (NOMBRE,ESTADO) VALUES ('compra FEBRERO 2017','pedido');
INSERT INTO PEDIDO (NOMBRE,ESTADO) VALUES ('compra MARZO 2017','pendiente');

INSERT INTO PRODUCTO(CODIGO_BARRAS,NOMBRE,MARCA,PRECIO) VALUES (977123456700C,"coca-cola","coca-cola",35.50,NULL,NULL);
INSERT INTO PRODUCTO(CODIGO_BARRAS,NOMBRE,MARCA,PRECIO) VALUES (582768419229C,"fideos","matarazzo",25.99,NULL,NULL);
INSERT INTO PRODUCTO(CODIGO_BARRAS,NOMBRE,MARCA,PRECIO) VALUES (252109313801C,"pan-lactal","bimbo",65.75,NULL,NULL);
INSERT INTO PRODUCTO(CODIGO_BARRAS,NOMBRE,MARCA,PRECIO) VALUES (8445940136801,"cerveza","antares",5.20,NULL,NULL);


