CREATE TABLE PEDIDO (_ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE TEXT, ESTADO TEXT);
CREATE TABLE PRODUCTO (_ID INTEGER PRIMARY KEY AUTOINCREMENT, CODIGO_BARRAS INTEGER, NOMBRE TEXT, MARCA TEXT , PRECIO REAL , CATEGORIA TEXT, DESCRIPCION TEXT);
CREATE TABLE SUPERMERCADO(_ID INTEGER PRIMARY AUTOINCREMENT, NOMBRE TEXT, DIRECCION TEXT, TELEFONO INTEGER, CORREO TEXT, LATITUD REAL, LONGITUD REAL);



